#!/bin/sh

# THIS SCRIPT SHOULD RECIDE INSIDE: ~/.local/bin

cd ~

# Log WLR errors and logs to the hyprland log.
export HYPRLAND_LOG_WLR=1

# XDG Specifications
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland

# Tell Xwayland to use a cursor theme
export XCURSOR_THEME=Bibata-Modern-Classic

# set a cursor size
export XCURSOR_SIZE=24

#IME Support
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus

# etc

export EDITOR=nvim
export VISUAL=nvim
export PAGER=less

# Preventing ranger from using default config. Uses ~/.config/ranger instead
RANGER_LOAD_DEFAULT_RC=FALSE

# QT theming
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt6ct
export QT_QPA_PLATFORMTHEME=qt5ct

exec Hyprland
